In [1]:
import numpy as np

In [5]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [59]:
np.arange(9,0,-1).reshape(3,3)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [57]:
np.linspace(1,9,9).reshape(3,3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [39]:
np.logspace(0,2,5,base = 2)

array([1.        , 1.41421356, 2.        , 2.82842712, 4.        ])

In [40]:
np.random.random((3,3))

array([[0.94297387, 0.52602036, 0.62295935],
       [0.46405307, 0.70749767, 0.60081303],
       [0.02052576, 0.52274504, 0.42774024]])

In [43]:
np.random.randint(1,9,size = (3,3))

array([[5, 8, 7],
       [7, 6, 4],
       [4, 5, 6]])

In [55]:
arr = np.random.randn(3,3)
arr2 = arr.astype(int)
print(arr2)
print(arr2.dtype)
print(arr)
print(arr.dtype)
print(arr.itemsize)
print(arr.size)
print(arr.shape)

[[-2  0  0]
 [ 0  0  0]
 [ 0  0  0]]
int32
[[-2.11777595 -0.40715233 -0.40340755]
 [ 0.56664829 -0.75171031 -0.55530131]
 [ 0.16335675  0.10811495  0.45721135]]
float64
8
9
(3, 3)


In [83]:
arr1 = np.array([
    [10,20],
    [30,40],
    [50,60]
])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr1)
print(arr2)

[[10 20]
 [30 40]
 [50 60]]
[[1 2 3]
 [4 5 6]]


In [86]:
np.dot(arr1,arr2)

array([[ 90, 120, 150],
       [190, 260, 330],
       [290, 400, 510]])